version: '3.1'
services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: omar
      MONGO_INITDB_ROOT_PASSWORD: 1
      MONGO_INITDB_DATABASE: testDB
    ports:
      - "27017:27017"

  app:
    build: .
    ports:
      - "5001:5001"
    depends_on:
      - mongo
    environment:
      MONGO_USERNAME: omar
      MONGO_PASSWORD: 1
      MONGO_DATABASE: testDB
      MONGO_HOST: mongo
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  mongo-data:
    driver: local

